version: '3.3'

services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python bot.py
    container_name: teamwork_parser_bot
    volumes:
      - .:/app:rw
    ports:
      - 8015:8000
    env_file:
      - ./.env