version: '3.7'

services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python bot.py
    volumes:
      - .:/app:rw
    ports:
      - 8015:8000
    env_file:
      - ./.env